# Generated by Django 2.2 on 2021-12-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_classics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_name',
            new_name='click_nums',
        ),
    ]
